version: '3'

services:
  web:
    build: build/nginx
    ports:
      - 80:80
      - 443:443
#      - "9000:9000"
    volumes:
      - ../:/var/www/html/
#      - ./conf/apache:/etc/apache2/sites-enabled/
      - ./conf/nginx:/etc/nginx/sites-available
      - ./shared:/shared
  php:
    build: build/php7.2
    volumes:
      - ../:/var/www/html/
      - ./conf/php7.2:/etc/php/7.2/cli/
      - ./shared:/shared
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql/
      - ./conf/mysql:/etc/mysql/
      - ./shared:/shared
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main_user
      MYSQL_PASSWORD: main_password
      MYSQL_ROOT_PASSWORD: root_password
#  cache:
#    image: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./cache:/data
#      - ./shared:/shared
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#  memcached:
#    image: memcached
#    ports:
#      - 11211:11211
#    volumes:
#      - ./shared:/shared
#    environment:
#      - MEMCACHED_USERNAME=root
#      - MEMCACHED_PASSWORD=root_password
#      - MEMCACHED_MEMORY_LIMIT=128
#  elasticsearch:
#    image: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
