services:
  web:
    build: build/nginx
    ports:
      - 80:80
      # - 443:443
      - 8000:8000
#      - "9000:9000"
    volumes:
      - ../backend:/var/www/html
      - ./conf/nginx:/etc/nginx/sites-available
      - ./shared:/shared
    depends_on:
      - php

  php:
    build: build/php8.1
    volumes:
      - ../:/var/www/html/
      - ./conf/php8.1:/etc/php/php8.1
      - ./shared:/shared
    # depends_on:
    #   - db

  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql/:rw 
#      - ./conf/mysql:/etc/mysql/
      - ./shared:/shared
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main_user
      MYSQL_PASSWORD: main_password
      MYSQL_ROOT_PASSWORD: root_password
